### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by PerferctGerund** [pohmelie/tinyantigate#2]
Please add requirements.txt in the root of the project and insert into this file following line:
`requests==2.X.X`(replace X with the latest or preferred version numbers)

**Comment by pohmelie** [comment]
Why this requires `2.9.1`?

**Comment by PerferctGerund** [comment]
I made a mistake, sorry.
I've edited my issue.

**Comment by pohmelie** [comment]
So this issue not relevant to this project? I can close this?

**Comment by PerferctGerund** [comment]
It's relevant for people who haven't `requests` lib.
Just choose one from requests versions (which you want) and add this file

**Comment by pohmelie** [comment]
I think it's enough to add plain `requests` without version, isn't it?

**Comment by PerferctGerund** [comment]
But the latest hot release may have a bug. (But for `requests` explicitly specify version is not so important)
So yes, add plain `requests`
